### ISSUE TITLE
Old Kiwix desktop versions in ppa repository, blocker for inclusion in Labdoo / Ubuntu (report from Mastodon user)

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-desktop#1020]
Report from a Mastodon user:

> Hi, Labdoo / Ubuntu was updated from kiwix.2.1 to kiwix.2.2. Kiwix.2.2 requires libkiwix11 as a dependency, but during the update the version libkiwix10 13.00-jammy was installed and the whole thing doesn't want to work together. Actually this should not happen because we install kiwix from a ppa. But you are not in it. Do you have the bug on your screen? Is a patch planned? Thank you.
>
> PS Labdoo uses 22.04 LTS. Kiwix.2.2 needs libkiwix11, but 22.04 LTS latest patch still comes with libkiwix10 13.00-jammy.

This user doesn't have a GitHub account, so couldn't make a report themselves. Is this fixable?

**Comment by kelson42** [comment]
I'm not even sure there is a problem... I believe what is reported is that kiwix-desktop 2.3 does not work with libkiwix 13... which would be not normal... bit not even sure this is the reported problem.

**Comment by Jaifroid** [comment]
I'm only passing on the message, but clearly Kiwix Desktop (or that old version) is showing package dependency errors, meaning it is blocked from inclusion in Labdoo, and possibly Ubuntu 22.04 LTS repositories, which presumably is undesirable for a Linux app. The reporter is a maintainer of Labdoo (I believe). It sounds like it's an issue, but perhaps it should be addressed by updating the version in the ppa to the latest (2.3.1-2).

**Comment by Jaifroid** [comment]
Some detailed info on this issue reported here:

https://platform.labdoo.org/content/kiwix-offline-tool-not-starting-after-ubuntu-update-kiwix-tool-startet-nach-ubuntu-update

**Comment by kelson42** [comment]
@legoktm @rgaudin @mgautierfr @veloman-yunkan It seems to me we have problem with how the Ubuntu PPA deb [control](https://github.com/kiwix/kiwix-desktop/blob/main/debian/control) file is set:
* No dependency to `libzim-dev` but there is not problem here
* Use of `~` which is unnecessary here as we don't do multiple builds in the PPA. But I wonder if as well is does not makes problem with minor and patch version of the dependency?! But here again this is not the problem.
* There is no "top limit" of the dependency (for example for the `libkiwix-dev`), which means that if a new release of `libkiwix-dev` is made but no new (patched) version of the `kiwix`, then `kiwix` will rely on the latest version of the libkiwix... and fails because the API/ABI has changed!

Would you be able to enlight me a bit as this is a general problem we probably have (if I get it right).

**Comment by Jaifroid** [comment]
Further info from a Labdoo technical person posting on Mastodon (translated from German, original is on Mastodon):

> It is probably due to the version of openssl that Kiwix uses to contact the server on which the .zims are located. Kiwix is currently compiled with openssl-1.1 for various reasons, but the current version at *buntus is already openssl-3... . And they don't want to work together :-)) . 
> https://github.com/kiwix/kiwix-desktop/issues/871
> 
> https://github.com/OpenChemistry/avogadrolibs/issues/1464
> 
> According to the threads, the problem lies with the QT libraries used, which have to be compiled with openssl-1.1.

**Comment by kelson42** [comment]
I don't have got any feedback here, so will just make a PR.
