### ISSUE TITLE
left tree disappears when toggling reading list

### ISSUE THREAD

**Issue by soloturn** [kiwix/kiwix-desktop#104]
left tree disappears when toggling reading list. on arch linux with kiwix-desktop_x86_64_2.0-beta1.appimage.

![image](https://user-images.githubusercontent.com/825568/52500812-229e1e80-2bdf-11e9-9b62-eefd89a08de6.png)

![image](https://user-images.githubusercontent.com/825568/52500787-14e89900-2bdf-11e9-849c-8bccb654b7d1.png)

![image](https://user-images.githubusercontent.com/825568/52500829-27fb6900-2bdf-11e9-945e-fd94557226c0.png)

**Comment by kelson42** [comment]
@soloturn I can not reproduce the problem with the beta2
@mgautierfr @schoenbaechler Does that make sense to keep the reading list button active when the library is displayed?

**Comment by soloturn** [comment]
i tried beta2 flatpack. it looks different, but i am not sure what is the version change, and what is the flatpack - appimage difference:

- the reading list button does do nothing
- the sizes of tab and menu fonts are correct. 
- after download the file does not show up file in "local files", i need to re-launch kiwix to see it
- it seems to use a different directory than the appimage so i cannot see the file downloaded with the appimage kiwix
- after installing flatpack, the appimage kiwix opens with a black window

hmm. will reboot. maybe its windows.

**Comment by kelson42** [comment]
@soloturn I understand that Kiwix Desktop can have many weaknesses, but please open one ticket per problem, otherwise this is really difficult to handle. Testing now with rc3.

> i tried beta2 flatpack. it looks different, but i am not sure what is the version change, and what is the flatpack - appimage difference:
> 
>     * the reading list button does do nothing

It is now deactivated if the library is displayed, which seems to me the correct behaviour.

>     * the sizes of elements around icon and menu items are correct. font sizes also. see the tab with the bird in this screenshot and the appimage screenshot as comparison

The tab size of the library (with the Kiwix logo) has now a proper size. I don't understand the problem around font size. If we still have a problem, a dedicated ticket should be opened.

>     * after download the file does not show up file in "local files", i need to re-launch kiwix to see it

This has been reported separatly in #240 ... and fixed.

>     * it seems to use a different directory than the appimage so i cannot see the file downloaded with the appimage kiwix

Yes, this is documented here https://github.com/kiwix/kiwix-desktop/wiki/Kiwix-desktop-on-an-USB-Drive-(Portable-version)

>     * the menu items "browse by category", "language", "content type" are not active, just as with appimage

This should work now

>     * after installing flatpack, the appimage kiwix opens with a black window

I can not really reproduce the problem (anymore), could you please open a dedicated ticket with the step-by-step procedure.

> should we close this? or just leave it open and look if the next appimage in nightly fixes it? currently i cannot find one and i am wondering where i got the beta1 appimage from.

I think we can close the ticket now as most of the problems have been fixed. @soloturn Would be great if you could test again and open new tickets if you find other bugs.
