### ISSUE TITLE
UI/UX issues with the reading list

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1078]
Currently the reading list is implemented as a sidebar of fixed width in a content tab. When switching to another tab the reading list disappears (and is not restored when returning to the same tab). The sidebar nature of the reading list suggests that selecting a bookmark should load it in the current tab, yet a new tab is opened instead.

The reading list cannot be opened (directly) while on the library tab (the workaround is to open a new empty tab, whereupon the reading list button is activated, but, again, the empty tab is not used to display the target of the bookmark).

**Comment by sgourdas** [comment]
@veloman-yunkan is the expected behavior for the reading list to stay attached to the tab in which it was opened from, until closed by the user? 
e.g. 
- Open tab x
- From tab x, open the reading list
- Open an item from the reading list (by default to a new tab y)
- **Returning to tab x the reading list is still open or closed?**

**Comment by kelson42** [comment]
Here is the only visual input we have as guidance:
![image](https://github.com/kiwix/kiwix-desktop/assets/1029718/d4ec4b33-af5c-4aaa-8ca7-b35adda07dad)

Here my remarks:
* We can see the quite high visual difference between what we have and the goal!
* The reading list side should not conceptually or from a user perspective depends from a tab
* It should be kept open whatever what we do with tabs
* Opening a bookmark should open in current tab or in a new tab if double-clikck (mouse middle-click)
* Regarding handling around library tab: I would just hide the sidebar when displaying library tab and display it otherwise.

**Comment by sgourdas** [comment]
@kelson42 I have made a PR implementing the pinning of the reading list.

Regarding your 4th point
> Opening a bookmark should open in current tab or in a new tab if double-click (mouse middle-click)

For me at least, on the current implementation, when single or middle clicking on a reading list element, nothing happens. The only thing that works is double clicking, where the element is opened in a new tab. Do we want to change this?

**Comment by kelson42** [comment]
> > Opening a bookmark should open in current tab or in a new tab if double-click (mouse middle-click)
> 
> For me at least, on the current implementation, when single or middle clicking on a reading list element, nothing happens. The only thing that works is double clicking, where the element is opened in a new tab. Do we want to change this?

Indeed:
* Simple click should open in current tab
* Double-click AND middle-mouse-clikc should open in new tab

**Comment by veloman-yunkan** [comment]
> * Regarding handling around library tab: I would just hide the sidebar when displaying library tab and display it otherwise.

@kelson42 What's the problem with displaying the reading list alongside the library tab?

**Comment by sgourdas** [comment]
@veloman-yunkan essentially the side panel of the library tab and the reading list is the same element with different contents, so despite cluttering I think it would be weird to implement

**Comment by veloman-yunkan** [comment]
@sgourdas I thought so too when I was about to raise my concern, but I checked and it seems that it's not the case: https://github.com/kiwix/kiwix-desktop/blob/017218478b89c247ddcb5b86b5b4e9abc5023a3a/ui/mainwindow.ui#L70-L78

**Comment by veloman-yunkan** [comment]
> @sgourdas I thought so too when I was about to raise my concern, but I checked and it seems that it's not the case:
> 
> https://github.com/kiwix/kiwix-desktop/blob/017218478b89c247ddcb5b86b5b4e9abc5023a3a/ui/mainwindow.ui#L70-L78

Ok, now I see why I was wrong.

```
$ grep -w sideBar src/mainwindow.cpp 
    mp_ui->sideBar->setCurrentWidget(mp_ui->contentmanagerside);
        mp_ui->sideBar->setCurrentWidget(mp_ui->readinglistbar);
        mp_ui->sideBar->show();
        mp_ui->sideBar->hide();
        mp_ui->sideBar->setCurrentWidget(mp_ui->contentmanagerside);
        mp_ui->sideBar->show();
        mp_ui->sideBar->hide();
```

**Comment by sgourdas** [comment]
Yes, both elements are loaded on the sideBar so I am not sure how we would get around that in a simple way

**Comment by veloman-yunkan** [comment]
They can simply be displayed side by side rather than in a stacked widget. @kelson42 What do you think about it?

**Comment by veloman-yunkan** [comment]
@kelson42 Review done
