### ISSUE TITLE
Book description misbehaves on hover

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1112]
[Screencast from 05-17-2024 02:16:50 PM.webm](https://github.com/kiwix/kiwix-desktop/assets/11933502/5b1811e3-59cb-4322-bbc9-44268253a8af)

**Update 2024-05-22**: As first noted in #1115, another bug is that clicking the description row within the range of the open/download action column results in a crash.

**Comment by kelson42** [comment]
@ ShaopengLin  Would you be able to fix that one quickly please?

**Comment by ShaopengLin** [comment]
The '@' failed but gladly I looked over here :). I will investigate this. From what I recall, the column behavior in Qt's MVC is tricky.

**Comment by ShaopengLin** [comment]
The best I will be able to do is this due to Qt's stubbornness in only allowing the first column to span.
![Screenshot from 2024-05-21 22-34-32](https://github.com/kiwix/kiwix-desktop/assets/39098000/b3d7d91b-6a8d-4dc6-90a3-e70ad2fb1761)

Before:
![Screenshot from 2024-05-21 22-35-07](https://github.com/kiwix/kiwix-desktop/assets/39098000/f92a33c7-c548-4977-986f-92daac5bcc3d)

Another option is to keep the description in the **Name** column and word wrap. When the user drags the window out, it is technically, the only column that will expand. 
![Screenshot from 2024-05-21 22-38-45](https://github.com/kiwix/kiwix-desktop/assets/39098000/75da29cc-bb19-4a36-aae4-9a15dd2081b5)

**Comment by ShaopengLin** [comment]
Ignore my previous comment. I am able to actually replicate the same behavior. The PR should be coming soon.

**Comment by veloman-yunkan** [comment]
It seems that the hover issue comes with a newer version of Qt 5.15.3 (used in Ubuntu 22.04 jammy) and is absent in the older version of Qt (5.12.8) used in Ubuntu 20.04 focal. At least the appimage build of kiwix-desktop doesn't have it.
