### ISSUE TITLE
Download has stopped in the middle without any error

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1127]
I have experienced a strange scenario:
* Download via the internal library a ZIM file, around 3 GB
* The download finished
* When I open the file, the app crash

The reason is that actually the download has stopped in the middle and the file is corrupted, here the details:
https://tmp.kiwix.org/corrupted_zim_crash/

I expect:
The download should go to the end or stop with a proper error.

Remarks:
* Regarding the fact that the libzim should not crash: https://github.com/openzim/libzim/issues/893
* Regarding the fact that the app should not crash when I relaunch it: https://github.com/kiwix/kiwix-desktop/issues/1128

**Comment by kelson42** [comment]
@veloman-yunkan Do you believe the recent merge of #1118 might have fixed that issue?

**Comment by veloman-yunkan** [comment]
@kelson42 I don't think so, but mainly because I am uncertain if we are talking about a reproducible bug in `kiwix-desktop`. The bug report describes a single case (as long as the completed download is concerned) and it's not clear if that was a glitch in our app, in aria2c, in the OS/filesystem, hardware or something else. Bugs should be investigated/looked into if they can be reproduced.

**Comment by kelson42** [comment]
@veloman-yunkan I can definitly not reproduce that bug, therefore my question. If we have no scenario in mind what should we do next?

**Comment by veloman-yunkan** [comment]
@kelson42 Maybe close with a "cannot reproduce" comment?
