### ISSUE TITLE
Pressing ENTER in the search bar opens the first suggestion

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-desktop#1230]
#1224 broke the handling of pressing ENTER in the search bar - it always opens the first suggestion (even if it doesn't fully match the text in the searchbar).

_Originally posted by @veloman-yunkan in https://github.com/kiwix/kiwix-desktop/issues/1224#issuecomment-2435785981_

**Comment by ShaopengLin** [comment]
@veloman-yunkan Since we opened this issue I am continuing discussion here. From https://github.com/kiwix/kiwix-desktop/pull/1189#issuecomment-2436320701, it is found that QCompleter's activate signal is not sent on the invalid index so it doesn't work. This approach is inherently wrong since during typing, the m
odel is not cleared, which means not checking text match in openCompletion will cause us to open from no longer relevant suggestions.

Regardless, to ensure correctness, openCompletion() needs to check the text content before opening the index. One change could be that we make getDefaultSuggestionIndex more generalized:

![Image](https://github.com/user-attachments/assets/c1c2d152-ed9b-410f-af7e-2c9bebc70b34)
![Image](https://github.com/user-attachments/assets/d0a1a71e-f5dc-4bea-a6bb-62facaaf3a9b)

Then, we simply 
![Image](https://github.com/user-attachments/assets/23a8ae15-a5e1-46f9-a6af-32336b7b19cd)

**Comment by veloman-yunkan** [comment]
Another approach is to track if suggestions are valid (have already been produced) for the current content of the searchbox. If so, then `QLineEdit::returnPressed` should immediately result in `openCompletion(getDefaulSuggestionIndex());`

**Comment by ShaopengLin** [comment]
@veloman-yunkan This would result in the issue I described above:

> the model is not cleared until typing is finished, which means not checking text match in openCompletion will cause us to open from no longer relevant suggestions.

If we open in `returnPressed`, then we might open a suggestion during typing which is exactly what the m_returnPressed is trying to avoid.

**Comment by veloman-yunkan** [comment]
@ShaopengLin That's why my proposal is centered around tracking relevance of suggestions - though I used a somewhat ambiguous adjective [_valid_](https://en.wiktionary.org/wiki/valid#Adjective), which may have confused you, I meant it in the meaning _relevant_. The parenthesized fragment may have added to the confusion. Please reread my idea as follows

> Another approach is to track if suggestions are valid/relevant for the current content of the searchbox

With more detailed outline for a possible implementation:

1. Add a data member `m_suggestionsAreValidFor` that holds the searchbox text for which the most recent call of `onInitialSuggestions()` has taken place
2. In `QLineEdit::returnPressed` check if the current content of the searchbox matches `m_suggestionsAreValidFor`. If yes, call `openCompletion(getDefaulSuggestionIndex());` immediately.

That's the main idea. You may have to take into account a couple of edge cases (like the searchbox being empty, etc).

But I would like to see both fixes (as separate commits in one PR) so that we can select the better one.
