### ISSUE TITLE
2.0-rc2 appimage fails to start on Ubuntu 19.04

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-desktop#256]
On an almost fresh Ubuntu 19.04 install, kiwix-desktop fails to launch apparently missing aria2.
rc1 starts as expected on the same computer.

Pretty sure this version started on my Ubuntu 19.04 VBox VM though…

![Capture d’écran de 2019-09-16 11-48-34](https://user-images.githubusercontent.com/57929/64976745-9a34da00-d8a1-11e9-85ba-54a098ee711f.png)

**Comment by kelson42** [comment]
Works for me on 18.04...

**Comment by mgautierfr** [comment]
I confirm the issue. This is because of https://github.com/kiwix/kiwix-lib/commit/351e573bce1f728dcd1c43c24560ffbd05a79513

We use the executablePath both to detect local `library.xml` (provided by the user) and `aria2c` (included in the appimage archive). If we change the detection for one, we will break the other.

If you have a system wide aria2c installed, it will be used (and so it "works").

**Comment by kelson42** [comment]
@mgautierfr Sounds critical to me :(

**Comment by mgautierfr** [comment]
I agree

**Comment by mgautierfr** [comment]
Please test with 2.0-rc2-1

**Comment by rgaudin** [comment]
Works! thanks.
