### ISSUE TITLE
App icon does not render well on dar background

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#32]
I propose instead to use:
https://github.com/kiwix/apple/blob/master/macOS/Assets.xcassets/icon.appiconset/KIWIX-icon-1024-512%402x.png

**Comment by schoenbaechler** [comment]
hey @kelson42 and @mgautierfr, I explored some possibilities:

![app-icon-01](https://user-images.githubusercontent.com/5031003/46893401-c4367e80-ce3e-11e8-8604-7a2f14d3fb1c.png)
![app-icon-02](https://user-images.githubusercontent.com/5031003/46893402-c4367e80-ce3e-11e8-990e-4e5d8158c926.png)
![app-icon-03](https://user-images.githubusercontent.com/5031003/46893403-c4367e80-ce3e-11e8-9db9-f7a93e2a7bd1.png)

`app-icon-01.png` is using @kelson42’s suggested png. The others are using a white background. I suggest to go with the icon in `app-icon-02.png`. The background shape as a circle feels natural since the Kiwix logo bases on circles as well. It nicely complements the logo and makes sure that its usable across platforms and different backgrounds. [Here’s download link for the circle app icon as an svg](https://www.dropbox.com/s/h57tnhln9cwd44t/kiwix-app-icon.svg?dl=0).

**Comment by kelson42** [comment]
@schoenbaechler Thx. To me, the last one is the better, but the second one is OK too.

**Comment by schoenbaechler** [comment]
Hi @kelson42, thanks for the feedback, [here’s the download link for the square app icon](https://www.dropbox.com/s/krllajneu0ec8ce/kiwix-app-icons-square.svg?dl=0). I’m also fine with either, you might try both and see which one works best on all supported platforms.

**Comment by kelson42** [comment]
@schoenbaechler Square version has been put in alpha4 by @mgautierfr. Problem solved :)
