### ISSUE TITLE
wayland file menu positioning error

### ISSUE THREAD

**Issue by soloturn** [kiwix/kiwix-desktop#337]
when running kiwix-desktop on wayland, gnome or weston, opening the menu, and there the "file" menu displays the error:

```
qt.qpa.wayland: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x55c372502e60) 
which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x55c375cd3800) 
According to the xdg-shell protocol, this is not allowed. The wayland 
QPA plugin is currently handling it by setting the parent to the topmost 
grabbing popup. Note, however, that this may cause positioning errors 
and popups closing unxpectedly because xdg-shell mandate that child 
popups close before parents
```

in gnome when beeing on the right parent of the screen this leads to positioning errors so the file menu is somewhere on the screen, not attached to the main menu any more.

i saw a similar error with qt applications avidemux and k3b, so i am unsure if this is a qt bug or its in kiwix.

**Comment by soloturn** [comment]
i saw this is a QT error:
https://bugreports.qt.io/browse/QTBUG-68636

**Comment by kelson42** [comment]
I will have a look in details later.

**Comment by kelson42** [comment]
@soloturn What is your exact OS?

**Comment by soloturn** [comment]
arch linux. ah, you mean this sentence from johan helsing:
" 2. Make sure widgets have sensible transientParents, and Qt Wayland will happily use that."

```
gnome-shell 1:3.34.2-1
qt5-base 5.14.0-1
```

**Comment by kelson42** [comment]
@soloturn You use an AUR package which is not maintained by us. You should complain first to the maintainer as we don't really see the problem by us. In general these kinds of bug are related to older versions of Qt, see https://github.com/kiwix/kiwix-build/issues/403.

Please check our Flathub package and tell us if you have problems https://flathub.org/apps/details/org.kiwix.desktop. It should work, open or reopen the ticket otherwise.
