### ISSUE TITLE
Compiling issues under Arch (gcc8)

### ISSUE THREAD

**Issue by THS-on** [kiwix/kiwix-desktop#37]
I had some issues with building kiwix-desktop under Arch Linux.
First $$QMAKE_LUPDATE and $$QMAKE_LRELEASE  were not set. But this was an easy fix.

It only builds with `qmake QMAKE_CFLAGS_ISYSTEM=` because -isystem works differently in gcc8.

Scaling is wrong on my machine and `QT_AUTO_SCREEN_SCALE_FACTOR=0` helps with that.

Now it works and it's looking a lot better than the old version.

**Comment by kelson42** [comment]
@THS-on Have you tried with kiwix-build (this is the recommend way of compiling kiwix-desktop)?

**Comment by mgautierfr** [comment]
This is because of this https://github.com/kiwix/kiwix-build/blob/bd33238d60233f7c33609f2a96590072567bf5d3/kiwixbuild/builder.py#L22

This is to avoid an invalid cross-compilation (* from osx or ios from linux).

You may try to add `'arch'` to the `compatible_host` in `kiwixbuild/platforms/native.py` and `kiwixbuild/platforms/neutral.py`.
I have not tested kiwix-build on other distribution than fedora and ubuntu. The problem I can see for now is about installing needed packages.
If you try `kiwix-build` again on `arch`, do not hesitate to create an issue on `kiwix-build` repository.

**Comment by THS-on** [comment]
I've tried that and it failed again. I'll open up a new issue on kiwix-build.

**Comment by kelson42** [comment]
@THS-on @mgautierfr What should we do with this issue?

**Comment by mgautierfr** [comment]
The issue opened on kiwix-build has been solved.
I suppose we are good here. I'm closing the issue.

**Comment by soloturn** [comment]
created https://aur.archlinux.org/packages/kiwix-desktop-git to also build out of the git repository, 2019-12-26 this builds. the arch linux 2.0-rc1 package build fails.
