### ISSUE TITLE
Black screen on videos

### ISSUE THREAD

**Issue by HHHLucho** [kiwix/kiwix-desktop#39]
The videos contained in certains ZIM files do not play, black screen instead, in some version sounds works with black screen : 
-Windows 7 Ultimate 64 bits with kiwix 0.9, no sound no videos
-Windows 7 ultimate 64 bits with kiwix 2.0 alpha, sound but still no video
-Edubuntu 14 no sound no videos
-edubuntu in kiwix-serve works fine

zim file 'c'est pas sorcier' 

hope I gave enough details to solve that issue

**Comment by kelson42** [comment]
OK, so we support only Kiwix Desktop 2.0 here. So the problem is no video with Kiwix 2.0 alpha3 on Ubuntu and Edubuntu with https://download.kiwix.org/zim/other/cest-pas-sorcier_fr_all_2018-06.zim

**Comment by kelson42** [comment]
@HHHLucho On Ubuntu, if you start Kiwix Desktop 2.0 alpha from the command line, do you see any error messages appearing on the terminal?

**Comment by kelson42** [comment]
I can not reproduce the pb on my Ubuntu 18.04, but I have the same problem on my Windows 10.

**Comment by edusup** [comment]
I have tested under Win10 different ZIM Files with Videos. On all the same Problem (Sound ok, but black Videowindows). Have tested with different players (VLC,Quicktime...) but no difference.
Used the kiwix-desktop_windows_x64_2.0-alpha3
- Is this a Codec or right Problem?
- Necessary to convert all Videos in another format?
- Missing functions with the Video Player (ChangeSize, Replay, Timeshift, Subtitel)
Can help to make more test's!

**Comment by kelson42** [comment]
@edusup It is not a right problem and it should work out-of-the-box. It is quite clear that something goes wrong in the decoding, but so far, this is not clear what.

**Comment by HHHLucho** [comment]
tried on a brand new install of win 10 pro 1803 version, and the beta 2, still no videos

**Comment by Bam92** [comment]
Still no solution?

**Comment by mgautierfr** [comment]
I've just tried with today daily build (2019-01-29) and TEDxLausanne2012 and everything seems to work.
I can read video, no black screen and I've got sound.

I'm using a virtual windows 10.

**Comment by mgautierfr** [comment]
I've got black screen (but sound) with wikimooc2

**Comment by mgautierfr** [comment]
It seems it is indeed a codec problem. And there is no easy solution here.

We may be able to have it but we will need to recompile QtWebEngine ourselves with the right compilation options (https://doc.qt.io/qt-5/qtwebengine-features.html#audio-and-video-codecs)
But, as said in the linked doc, we will have to acquire licenses to be able to distribute the proprietary codec libraries.
On the other side, iOS/macOS only support x264.

One solution would be to have two different video codecs for each video in a zim file. This way, the browser may choose the codec it can read. But it will double the size of the video, it is difficultly doable.

But, in any case, we CANNOT guaranty that any video we provide in a zim will be readable on all device.
It simply because codecs to use have not be standardized.
https://caniuse.com/#feat=mpeg4
https://caniuse.com/#feat=webm
https://caniuse.com/#feat=ogv

**Comment by Bam92** [comment]
What is the version of Kiwix is running [here](http://library.kiwix.org)? Because [Wikimooc2](http://library.kiwix.org/wikimooc_fr_all_2018-06/#1) is running well.

**Comment by mgautierfr** [comment]
This is kiwix-server.
It serves the files (the video files) without decoding it, and it is your browser that read and decode it (and so need the codec). You probably have a browser compiled/distributed with support of h264.

**Comment by Bam92** [comment]
Ok.

I'd like to build my own wikimooc2 zim. I want to test different format of videos. I'm sure that wikimooc zim was built from .webm videos. May be build it from other format and see the output?

But I fail to build it. zimwriterfs documentation only explains how to build html. Is there a link for videos or another tool?

ps: I tried with Kiwix 0.9 this is the error I get:
![wikimooc2-on-kiwix-0 9](https://user-images.githubusercontent.com/14941675/52279131-83202800-2961-11e9-95c4-f68703403f1d.png)

**Comment by kelson42** [comment]
This is code problem (H264). We have stop generating this kind of files and new ZIM files should work. See for example https://download.kiwix.org/zim/other/mali-pour-les-nuls_fr_all_2019-09.zim.
