### ISSUE TITLE
Missing (up-to-date) dependencies on debian 9.5 (stable)

### ISSUE THREAD

**Issue by dattaz** [kiwix/kiwix-desktop#40]
On debian 9.5 (stable), kiwix's appimage fail to start : 
```
$ ./kiwix-desktop_x86_64_2018-10-05.appimage 
./kiwix-desktop_x86_64_2018-10-05.appimage: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_kiwix-OwhChD/usr/bin/../lib/libpng16.so.16)
./kiwix-desktop_x86_64_2018-10-05.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_kiwix-OwhChD/usr/bin/../lib/libsystemd.so.0)
```

Debian version zlib : 1.2.8
Debian version glibc : 2.24-11+deb9u1

**Comment by kelson42** [comment]
@mgautierfr Would the flatpack package solve that pb?

**Comment by Bam92** [comment]
Since the release of Kiwix 2.0 alpha, I am having this same problem. Wondering if someone has resolved it.
After spending some hours on Internet, I could resolve the first issue with zlib following these [instructions](https://github.com/JuliaPy/PyPlot.jl/issues/151) (@zekeriyasari).
Can someone help? Or have already started Kiwix 2.0 appimage?

**Comment by kelson42** [comment]
The flatpak resolves that problem and we are not going to provide an appimage supporting an older version of glibc/zlib. Lets hope at the end, the native OS packages will solve perfectly this kind of problem, meanwhile people will have to use the flatpak file (with or without flathub) in that case.
