### ISSUE TITLE
Debian package name should better be "kiwix-desktop" ?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#504]
It is currently "kiwix"... but we have so many kiwix that years ago we decided to have more explicit name. Probably the package name should better reflect the official name?

**Comment by legoktm** [comment]
I didn't give much thought to this when adopting the previous kiwix packaging. Since we just reintroduced kiwix-desktop into Debian I think it should be straightforward to rename.

However, a [search](https://packages.debian.org/search?keywords=desktop&searchon=sourcenames&suite=stable&section=all) indicates that the `-desktop` suffix is primarily used by desktop environments (e.g. cinnamon, gnome, mate). I do see two exceptions in `nextcloud-desktop` and `telegram-desktop`.

My guess is that casual users looking for kiwix-desktop will likely to find a `kiwix` package and advanced users looking for something else will be able to figure out the difference. I can also improve the description to indicate that `kiwix` is the desktop client.

So I don't think `-desktop` is a good suffix for the Debian package. But I'll defer to whatever y'all prefer.

**Comment by mgautierfr** [comment]
I would follow the debian way to name their packages but I have no strong opinion here.

**Comment by kelson42** [comment]
@LAfricain You mean in our PPA? Then this is a question for @legoktm

**Comment by LAfricain** [comment]
No, I'm speaking about the debian repositories. This option will solve also the ppa "problem". I mean kiwix will be automatically in the Ubuntu repositories.

**Comment by kelson42** [comment]
@LAfricain It seems it is or will be available in buster-backports, see https://tracker.debian.org/news/1234765/accepted-kiwix-205-3bpo101-source-into-buster-backports/. In general rely to https://debian.kiwix.org/ to know what is the status of the Debian packaging.
