### ISSUE TITLE
Aborted downloads are not cleared from storage folder

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#54]
I suspect Kiwix crashed when I started several concurrent downloads (tbc): when reopening it, two of the files I had been downloading were listed as "local", yet obviously not downloaded
![image](https://user-images.githubusercontent.com/21675885/48047763-68d78200-e199-11e8-9823-04bdfd50712f.png)
Admittedly the download restarted where it left, so I'm not entirely sure if it is a bug or a feature.

**Comment by kelson42** [comment]
@jetownfeve21 Would be really nice if you could check this is still a valid bug.

**Comment by jetownfeve21** [comment]
If I start downloads, send a abort signal to simulate a crash and restart the app, these downloads aren't considered as finished and continue downloading. I think this has been fixed with this pr https://github.com/kiwix/kiwix-lib/pull/218 thanks to the check of the status with the tellWaiting() function
@kelson42

**Comment by kelson42** [comment]
@jetownfeve21 Thx for having again a look to that in details. I close the ticket first. Should be reopen if this kind of problem is reproduced with the next beta5.
