### ISSUE TITLE
Missing categories in Browse by Category list

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#552]
When trying to sort available files by category, several content categories are not listed and filterable, e.g. `videos`, `openedx`, `ted`, etc.
![image](https://user-images.githubusercontent.com/21675885/101652402-7b8aa800-3a3e-11eb-886c-c28f9252bd1f.png)

I am able to find TED videos, but considering the sheer volume of available file and the impossibility to sort I was not able to find any of the others.

**Comment by kelson42** [comment]
The categories are hardcode at the Kiwix level sofar. The library.kiwix.org does not deliver that information so far, see https://github.com/kiwix/kiwix-tools/issues/318. I believe we should quickly improve the hardcoded list to fill the gap by adding categories;
* TED
* Openedx
* Videos
* Gutenberg

**Comment by Popolechien** [comment]
Ah I see in https://github.com/kiwix/kiwix-desktop/blob/847dccddd80f31ddd3dc225216fa64b5be268acc/src/static_content.cpp
`//  PUSH("gutenberg"); // Gutenberg book has wrong tag`
`//  PUSH("phet"); // Phet books have no tags`
`//  PUSH("ted");  // Ted books have wrong tags`

**Comment by kelson42** [comment]
OK, will check if the problem at ZIM level is still actual and do the necessary.

**Comment by kelson42** [comment]
@Popolechien I checked a bit:
* TED can be reintroduced, tags are OK now
* Openedx, tags are NOK (currently in `other`) but probably better like this considering that we have only a few of them? It as well a tech platform and probably end-user does not care about that. Maybe "Mooc" would be a better category.
* Videos does not exists at all as a category in ZIM file. I would wait to get the CMS to handle that, otherwise we will have many scrapers to end.
* Gutenberg, something is wrong. See my comment https://github.com/openzim/gutenberg/issues/84#issuecomment-743773874

**Comment by Popolechien** [comment]
Yes openedx should be Mooc indeed.

**Comment by kelson42** [comment]
Gutenberg is fixed

**Comment by kelson42** [comment]
Looks like the last thing to do is to create a category “Mooc”. @rgaudin this will imply to change a few things on the ZIM toolchain. Do you believe this is a good idea?

**Comment by rgaudin** [comment]
I have no opinion on the pertinence of a `mooc` category. It's a content/distribution decision. But since it's the primary user-facing filter beside language in every reader, I'd advise to choose it wisely.

On the zim-creation side, there are two things:

- zimfarm has a *Category* which is used only for filtering purposes there. Not tied to ZIM category.
- some scrapers hardcode a category (reminder: category is just a tag) like sotoki or gutenberg.

We could imagine that we allow scraper users to customize the category in all scrapers. As this is just a tag, it would just mean ensure we don't enforce a category ourselves (sotoki, gutenberg). It might make sense for youtube which is just a platform but covers a lot of topics: some playlists could fit the *mooc* category.

Since those *moocs* are very limited and updating all readers is quite an effort, I'd prefer we layout a proper plan for Categories (what was discussed at Wikimania) and tie this with the upcoming CMS.

**Comment by kelson42** [comment]
@rgaudin Thank you for bring all my concerns here.

> I have no opinion on the pertinence of a `mooc` category. It's a content/distribution decision. But since it's the primary user-facing filter beside language in every reader, I'd advise to choose it wisely.

Yes and no, because this catogories should be soon be dynamically retrieved from the OPDS stream, see https://github.com/kiwix/kiwix-tools/issues/317.

> On the zim-creation side, there are two things:
> 
>     * zimfarm has a _Category_ which is used only for filtering purposes there. Not tied to ZIM category.

Yes, I'm not sure about the real future of this feature, the value seems limited (in addition to zimfarm tags, title search) and to some extend confusing (with ZIM categories and future CMS/reader categories).

>     * some scrapers hardcode a category (reminder: category is just a tag) like sotoki or gutenberg.

Yes, should stay.

> We could imagine that we allow scraper users to customize the category in all scrapers. As this is just a tag, it would just mean ensure we don't enforce a category ourselves (sotoki, gutenberg). It might make sense for youtube which is just a platform but covers a lot of topics: some playlists could fit the _mooc_ category.

Like you said earlier, this is ultimatively a decision of the CMS.

> Since those _moocs_ are very limited and updating all readers is quite an effort, I'd prefer we layout a proper plan for Categories (what was discussed at Wikimania) and tie this with the upcoming CMS.

Yes, but the fact that this will be made dynamic, I'm not really eager to start a big discussion on this now. Maybe this summer? one time the CMS is ready?

**Comment by kelson42** [comment]
openedx ZIM files now per default in the 'mooc' category, see https://github.com/openzim/openedx/commit/356f3f90e57ffb567b1754b28928b5df14ec092b.
