### ISSUE TITLE
In library, the two search boxes are confusing the user

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#554]
While looking at `All Files` I am dealing with hundreds of files if I am set to English. Typing a search for a given term should allow to filter results for that particular string.

**Comment by kelson42** [comment]
@Popolechien I guess you got confused beetween the content search and the library search box

**Comment by Popolechien** [comment]
Correct. I guess the Enhancement should be "Search for a zim title while View is on the library, search _in_ zim files when view is in a zim." This of a sort of drop-down menu to toggle searc range but that's more clunky

**Comment by kelson42** [comment]
@Popolechien What you propose is too complex IMO. Here is how the mockup looks like:
![image](https://user-images.githubusercontent.com/1029718/101879123-1b584b00-3b91-11eb-81e6-4bef162d068d.png)

**Comment by Popolechien** [comment]
And here is what we have: 
![image](https://user-images.githubusercontent.com/21675885/101881384-a2f38900-3b94-11eb-979b-25292af6f85a.png)

**Comment by suterma** [comment]
> @Popolechien I guess you got confused beetween the content search and the library search box

I can only second this. Any new user will be completely confused, what to search with each box, the placeholder text is not conculsive. Also, the very existence of two search bars on a screen should be avoided in the first place.

**Comment by kelson42** [comment]
@Popolechien @suterma So, the current implementation respects the UI design mockup! We need to agree if there is an implementation problem or a design problem... or both.

**Comment by suterma** [comment]
_Work in progress_
This comment proposes a concrete solution to the issue at hand. The aim is to somewhat mimick the behavior of the Firefox browser with regards to content and settings.

- The tabs bar is ALWAYS the topmost UI element.
- Below is some "menu bar" that displays the appropriate navigation within the visible tab's content.
- Below is the content, respective to the tab type.

Imho, these are the advantages:

- This design avoids the "double search bar"
- Since it is similar to an existing application, it does not reinvent the wheel much (Least Surprise)
- The displayed search bar is always where the searched items are (IN the tab, not above the tab bar)

Screen mockups:

:todo:

Clearly, this proposal is only a first draft, out of my own experience as a new kiwix user, and should be refined.

**Comment by kelson42** [comment]
@suterma Thank you for your proposal. This is an interesting one. But, honestly I don't fell comfortable to make such a massive change just right like this. This is too much, too quick, and from someone with too few experience with the project.

I propose an alternative which is easier and less risky:
* Move the library search bar to the left sidebar, below other filters
* Keep it like it is, but replace "Search files" with "Search catalog"
* Disable the top search bar, if in library. Activate otherwise

**Comment by kelson42** [comment]
For the documentation, here is how the Kiwix Desktop 1.0 library looked like:
![image](https://user-images.githubusercontent.com/1029718/126341993-28013cbf-d05c-46f0-b4aa-c789b3e5fb5d.png)

**Comment by kelson42** [comment]
@juuz0 @Popolechien Should we try to handle this now?

**Comment by Popolechien** [comment]
@kelson42 Sure thing.

**Comment by rgaudin** [comment]
@suterma 's version feels more natural to me; like Firefox.
Is there a search in page feature? So a potential for an additional search field? Firefox places this last one on the bottom.

**Comment by kelson42** [comment]
> Is there a search in page feature?

No, but this is a topic which will at some point tackle. I will open a ticket.

**Comment by juuz0** [comment]
Proposal 1 (https://github.com/kiwix/kiwix-desktop/issues/554#issuecomment-883387247) sounds good in combining the search bars, but the changing the placement of top search bar looks weird to me. The fullscreen and menu buttons also move with it. They are top-right in apps usually (atleast the fullscreen/maximize button).

Proposal 2 (https://github.com/kiwix/kiwix-desktop/issues/554#issuecomment-883440858) is more *natural* in the sense all filters are at the same area. Though, rather than disabling the top search bar, I think completely hiding it will be better? Same with hiding anything not useful (back button/forward button/ reading list button). I prefer this proposal.

**Comment by kelson42** [comment]
> Though, rather than disabling the top search bar, I think completely hiding it will be better? Same with hiding anything not useful (back button/forward button/ reading list button). I prefer this proposal.

Hidding will proably not happen as we can not hide everything. But greying yes. But for the searchbar, it will be soon a multizim searchbar and as such there won't be reason to grey it once this is implemented.

**Comment by juuz0** [comment]
>  But for the searchbar, it will be soon a multizim searchbar

This will outdate proposal 1 I think? How will multizim search and books filtering work with the same searchbar, if not.

**Comment by kelson42** [comment]
> > But for the searchbar, it will be soon a multizim searchbar
> 
> This will outdate proposal 1 I think? How will multizim search and books filtering work with the same searchbar, if not.

I don't think this make the request deprecated. Actually I'm almost convinced that having only one bar would be better. But what is sure, is that this has a lot of implication to have this kind of "Awesome bar" and we are definitly not mature for that.

I will open a dedicated ticket to that, but in the meantime please implement this ticket by moving the library search bar at the top of the side bar.
