### ISSUE TITLE
Add Ladakhi to language list

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#681]
We've got content in this language that cannot be retrieved in the app because Ladakhi is not an option from the language list.

**Comment by kelson42** [comment]
For the moment the list is hardcoded at the Kiwix-Desktop level. But since a few weeks @ veloman-yunkan has implemented in libkiwix the primitive to get the list of languages for which we have contents. This is available both at the ABI level and in a form of a REST API end-point.

So far this is used only by Kiwix-Serve to populate its welcome page filters selecboxes, but the goal is that the Kiwix Desktop relies on it as well. We will do so at the time we will revamp the library, see #683.
