### ISSUE TITLE
Add expand / collapse, zoom-in / zoom-out to right click menu

### ISSUE THREAD

**Issue by alex-ie** [kiwix/kiwix-desktop#698]
I noted tabs opened with expanded sections stay expanded when link within is clicked and those opened collapsed open new page in the tab when link is clicked collapsed. So tabs retain this (expand / collapse) attribute. If not burdensome to implement, I think it would benefit users to have expand / collapse options added to right-click menu so that page on the tab changed accordingly and the tab retained that attribute. 

Also zoom-in / zoom-out would be good to have here as it is long path to press from the menu (there are hot keys but as I mentioned "If not burdensome to implement"). (Might be worth separate issue, I just thought if change would be done to that menu to add these lines would be easier as part of one go). Thanks.

**Comment by kelson42** [comment]
@alex-ie Please "one topic per ticket".

**Comment by kelson42** [comment]
> I noted tabs opened with expanded sections stay expanded when link within is clicked and those opened collapsed open new page in the tab when link is clicked collapsed.

I can not reproduce this and this anyway not a feature if this would happen.

I'm against building it in the "right-click" context menu, because this menu should have nothing special related to kind of content. The collapsing of the content is special to Mediawiki based content.

Regarding the zooms, same: I'm against building it:
* This is not available in standard browsers
* There are already shortcuts like in a browser (with the keyboard or keyboard+mouse).
