### ISSUE TITLE
Remove status bar

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#71]
The status bar at the far bottom is always empty. So far I can see with the new UI design, there should not be any status bar at all. @schoenbaechler You confirm?

@mgautierfr depending a bit what @schoenbaechler means, but I would remove it or keep it in sync: display properly the url which is pointed to know where a link point to.

**Comment by schoenbaechler** [comment]
@kelson42, I confirm that the status bar hasn’t been considered in the designs. I just checked how Chrome and Firefox are handling this. The link is shown on hover & focus of a link. I think we should incorporate that behavior for external links. I’d advocate that it’s not necessity for links within the same ZIM file, since it wouldn’t provide any added value. It would add value if there are **cross** ZIM links, but that doesn’t exist to my knowledge, is that correct? Thanks.

**Comment by kelson42** [comment]
This has been implemented

**Comment by jetownfeve21** [comment]
@kelson42 What do you mean by "implemented" ? Should we keep the status bar or not ?

**Comment by kelson42** [comment]
@jetownfeve21 You have removed the status bar and are going to replace it with a proper tooltip with the URL. This is the ticket #209 (which is still open).

**Comment by jetownfeve21** [comment]
Finally I removed the status bar in another pr (https://github.com/kiwix/kiwix-desktop/pull/253)
