### ISSUE TITLE
Content Filtration

### ISSUE THREAD

**Issue by almuhder** [kiwix/kiwix-desktop#723]
This issue is related to explicit content rather than a technical issue, it might be a suggestion to have a '**Safe search**' feature when we search for images in Google. 

We are using Kiwix desktop as an offline app for kids, today we found there are a lot of images which are not suitable for kids. We know we have the Text-Only version, but this is not an option for us, as we believe in the importance of images for kids.

Is there a way to omit certain topics from the zim file? We are using the 'all maxi' one.

**Comment by kelson42** [comment]
I guess you talk about Wikipedia in Arabic offline?

**Comment by almuhder** [comment]
Yes, exactly!

**Comment by kelson42** [comment]
The problem is the content, not the tool. Wikipedia is for adults, or maybe teenagers. This is not a encyclopedia for childrens. As such there is a lot of content which is probably not appropriate for them. What you need is an encyclopedia in Arabic for children. We have a few small ones (Vikidia) but none in Arabic unfortunately.
