### ISSUE TITLE
Release repository on Ubuntu still has a version of kiwix-desktop that gives the "not enough storage available" error 

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-desktop#926]
Received this email, logging it here for the record:

> Just wanted to let you know that your release repository on Ubuntu still has a version of kiwix-desktop that gives the `not enough storage available` error (https://github.com/kiwix/kiwix-desktop/issues/854).
> I removed that repo and used the development one to install kiwix-desktop and it works fine now. But many people may not know to do this.```

**Comment by kelson42** [comment]
We are aware and what shoukd have been foxed has been fixed.

**Comment by mgautierfr** [comment]
It seems that the official package on ubuntu is the kinetic one (https://packages.ubuntu.com/kinetic/kiwix) and is in version `2.2.2`.

The fix is indeed in `2.3.0`

The dev ppa (https://launchpad.net/~kiwixteam/+archive/ubuntu/dev) is ok
But the release ppa (https://launchpad.net/~kiwixteam/+archive/ubuntu/release) is **NOT** as the package workflow was broken when we have make the `2.3.0` and `2.3.1` releases
