### ISSUE TITLE
kiwix can not launch on Windows10.

### ISSUE THREAD

**Issue by FishXD** [kiwix/kiwix-desktop#935]
![kiwix problem](https://user-images.githubusercontent.com/53416928/232775777-67625c66-590b-4bbd-9fd1-424abe2a9aac.gif)
last week the kiwix is great, but yesterday when i use it i fund it doesn't work on win10. like the gif. what should i do?
my laptop is win10, 21H2,  19044.2846.
And use kiwix-desktop_windows_x64_2.3.1.

**Comment by Jaifroid** [comment]
@FishXD I've now had a chance to test 2.3.1 under Windows 10 desktop. It runs fine for me, but Windows asked me to change a setting (see below). Under Settings -> Apps & Features, I had to change "where to get apps" from "Microsoft Store only" to "Anywhere". However, it guided me to do this, so it's not a big issue, and is a one-time setting. Probably because this app doesn't have a signed installer and is merely unzipped, so it's a security measure. Please verify your setting.

![image](https://user-images.githubusercontent.com/4304337/233599048-fa35512c-114a-462f-9ae8-ae1d786bba78.png)

**Comment by Jaifroid** [comment]
PS Just to clarify, the executable itself is correctly signed with a Kiwix signature. I was referring to the lack of an installer.

**Comment by ilmist** [comment]
@FishXD Have you fixed this issue? I have the same problem as you:(

**Comment by kelson42** [comment]
Unfortunately, no feedback of the user. We have to close the ticket without more information.
