### ISSUE TITLE
Kiwix Desktop on Windows does not recognize ZIM-files in directory

### ISSUE THREAD

**Issue by lsolesen** [kiwix/kiwix-desktop#937]
When I put ZIM-files downloaded elsewhere, the ZIM-files are not recognized on Windows 11 in the most current Kiwix '2.3.1'.

Only the ZIM-files downloaded by Kiwix is on the list over Local Files.

<img width="940" alt="kiwix-desktop_gWGqpLrc1W" src="https://user-images.githubusercontent.com/148026/235431884-a6d553d0-66cb-487a-994e-f254185d7c9b.png">

However, this is my directory:

<img width="597" alt="explorer_S7iOwPy9Ip" src="https://user-images.githubusercontent.com/148026/235431965-659b3052-9b00-48cf-87e3-fddf1048be29.png">

I have setup my 'Monitor directory' to the folder with the ZIM-files. However, they are not recognized.

However, the files are picked up by the 'libray.xml'.

<img width="663" alt="Code_d6Is9KN4En" src="https://user-images.githubusercontent.com/148026/235432353-6aa5f0f5-78ae-4661-895e-91c6ebddb735.png">

So what can be the reason, that they are not showed under the Local Files in the Kiwix Desktop?

**Comment by gmikhail** [comment]
I think this topic can be closed because most likely the problem is in the crooked language filter (when Kiwix after launch shows only ZIM files in OS language). https://github.com/kiwix/kiwix-desktop/issues/902#issuecomment-1319674481

As proof of this theory, only ZIM files in the `de` language are displayed on the user's screenshot. I will assume that the Kiwix and OS interface is displayed in the same language.

**Comment by lsolesen** [comment]
You are right about the filter. I think for local files that it would be
nice that all files show, and the you can apply a filter, if you only want
to see some of your local zims.

søn. 14. maj 2023 19.02 skrev Mikhail Gribanov ***@***.***>:

**Comment by kelson42** [comment]
Duplicate
