### ISSUE TITLE
Add the navigational templates from the Wikipedia pages

### ISSUE THREAD

**Issue by Shenmue-is-life** [kiwix/kiwix-desktop#993]
**Navigational templates**, also known as "**navboxes**", are the boxes full of internal URLs you usually find at the end of some Wikipedia pages to facilitate navigation between the most related articles.
https://en.wikipedia.org/wiki/Wikipedia:Navigation_template

I believe it's the most lacking part of the Kiwix articles with hi-res images. But unlike the latter, the former should be easier to integrate.

Same could be said for the "**Categories**" box but they are less essential in my view.
https://en.wikipedia.org/wiki/Help:Category

**Comment by kelson42** [comment]
@Shenmue-is-life I will move the ticket to the repository `openzim/mwoffliner` which is the scraper in charge of the content.

That said there is IMO not much we can do as we take the HTML like it is delivered from the Wikipedia mobile API. I will still verify.

**Comment by Jaifroid** [comment]
@Shenmue-is-life I realize you opened this a few weeks ago, but could you say which Wikipedia ZIM you are using, because AFAIK most navboxes should now be displaying in all Kiwix browsers? Below is a recent Wikipedia ZIM article showing in Kiwix Desktop (left) and the PWA version (right) and in both, you can clearly see the navbox on the right (Years in film).

FYI the PWA (https://pwa.kiwix.org) has an option to search for and display any hidden navboxes and categories lists (the options is on by default), and this can be used to check whether the ZIM actually contains them or not. You can also switch to desktop style in the PWA, which is designed to show all content by default. In the Wikipedia mobile style, some elements are hidden by design.

See also https://github.com/openzim/mwoffliner/issues/1493 and https://github.com/openzim/mwoffliner/issues/1435.

![image](https://github.com/kiwix/kiwix-desktop/assets/4304337/ece537f8-5be8-4a89-a44f-61f778c35efe)
